### PR TITLE
Added my backend with node js and express

### PR DESCRIPTION
**Pull request by rendivs925**
I havent added functionality for it

### CODE REVIEW

**Comment by MUYANGGUO** [comment]
@rendi12345678 This pull request is too large to review. Do you have a design doc?
And there are many open sourced dependencies introduced in this pull request, tho I haven't took a deep look, but I suspect that they are not necessary in this project. The backend would be preferred to be light weighted.

**Comment by MUYANGGUO** [comment]
hmmm, took a close look, these uploaded diff are actually are all node modules, could you gitignore the node modules.

**Review by lele94218 — CHANGES_REQUESTED** [review]
Please not modify current development setup if you don’t have to. Also not dump node libs here.

**Comment by rendivs925** [comment]
> hmmm, took a close look, these uploaded diff are actually are all node modules, could you gitignore the node modules.

ok i am forgot sir

**Comment by rendivs925** [comment]
> Please not modify current development setup if you don’t have to. Also not dump node libs here.

sorry i will make gitignore for it

**Pull request closed without merging**
